//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spectra.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveDirectory {
            get {
                return ((string)(this["SaveDirectory"]));
            }
            set {
                this["SaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public uint IntegrationTime {
            get {
                return ((uint)(this["IntegrationTime"]));
            }
            set {
                this["IntegrationTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint BackToBackPerTrigger {
            get {
                return ((uint)(this["BackToBackPerTrigger"]));
            }
            set {
                this["BackToBackPerTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint NumSpectraPerRequest {
            get {
                return ((uint)(this["NumSpectraPerRequest"]));
            }
            set {
                this["NumSpectraPerRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte BufferEnabled {
            get {
                return ((byte)(this["BufferEnabled"]));
            }
            set {
                this["BufferEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint ScansToAverage {
            get {
                return ((uint)(this["ScansToAverage"]));
            }
            set {
                this["ScansToAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte TriggerMode {
            get {
                return ((byte)(this["TriggerMode"]));
            }
            set {
                this["TriggerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte LampEnable {
            get {
                return ((byte)(this["LampEnable"]));
            }
            set {
                this["LampEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AcquisitionDelay {
            get {
                return ((uint)(this["AcquisitionDelay"]));
            }
            set {
                this["AcquisitionDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double AcquisitionDuration {
            get {
                return ((double)(this["AcquisitionDuration"]));
            }
            set {
                this["AcquisitionDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AcquisitionDurationIndex {
            get {
                return ((int)(this["AcquisitionDurationIndex"]));
            }
            set {
                this["AcquisitionDurationIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveToFile {
            get {
                return ((bool)(this["SaveToFile"]));
            }
            set {
                this["SaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public uint ArduinoTriggerDelay {
            get {
                return ((uint)(this["ArduinoTriggerDelay"]));
            }
            set {
                this["ArduinoTriggerDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectrumThresholdingEnabled {
            get {
                return ((bool)(this["SpectrumThresholdingEnabled"]));
            }
            set {
                this["SpectrumThresholdingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectrumThresholdingAllSatisfiedEnabled {
            get {
                return ((bool)(this["SpectrumThresholdingAllSatisfiedEnabled"]));
            }
            set {
                this["SpectrumThresholdingAllSatisfiedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExperimentInfo {
            get {
                return ((string)(this["ExperimentInfo"]));
            }
            set {
                this["ExperimentInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionsInfo {
            get {
                return ((string)(this["ConditionsInfo"]));
            }
            set {
                this["ConditionsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveStartPixel {
            get {
                return ((int)(this["SaveStartPixel"]));
            }
            set {
                this["SaveStartPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2135")]
        public int SaveEndPixel {
            get {
                return ((int)(this["SaveEndPixel"]));
            }
            set {
                this["SaveEndPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectrumFilteringEnabled {
            get {
                return ((bool)(this["SpectrumFilteringEnabled"]));
            }
            set {
                this["SpectrumFilteringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectrumFilteringAverage {
            get {
                return ((bool)(this["SpectrumFilteringAverage"]));
            }
            set {
                this["SpectrumFilteringAverage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpectrumFilteringGaussian {
            get {
                return ((bool)(this["SpectrumFilteringGaussian"]));
            }
            set {
                this["SpectrumFilteringGaussian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SpectrumFilteringSupport {
            get {
                return ((int)(this["SpectrumFilteringSupport"]));
            }
            set {
                this["SpectrumFilteringSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentPlotType {
            get {
                return ((int)(this["CurrentPlotType"]));
            }
            set {
                this["CurrentPlotType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveOnWrite {
            get {
                return ((bool)(this["SaveOnWrite"]));
            }
            set {
                this["SaveOnWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleSoftwareTriggerEnabled {
            get {
                return ((bool)(this["SingleSoftwareTriggerEnabled"]));
            }
            set {
                this["SingleSoftwareTriggerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContinuousStrobePulseEnabled {
            get {
                return ((bool)(this["ContinuousStrobePulseEnabled"]));
            }
            set {
                this["ContinuousStrobePulseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint ContinuousStrobePulsePeriod {
            get {
                return ((uint)(this["ContinuousStrobePulsePeriod"]));
            }
            set {
                this["ContinuousStrobePulsePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint ContinuousStrobePulseWidth {
            get {
                return ((uint)(this["ContinuousStrobePulseWidth"]));
            }
            set {
                this["ContinuousStrobePulseWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleStrobePulseEnabled {
            get {
                return ((bool)(this["SingleStrobePulseEnabled"]));
            }
            set {
                this["SingleStrobePulseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint SingleStrobePulseDelay {
            get {
                return ((uint)(this["SingleStrobePulseDelay"]));
            }
            set {
                this["SingleStrobePulseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint SingleStrobePulseWidth {
            get {
                return ((uint)(this["SingleStrobePulseWidth"]));
            }
            set {
                this["SingleStrobePulseWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastPlotType {
            get {
                return ((int)(this["LastPlotType"]));
            }
            set {
                this["LastPlotType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("157.3")]
        public double SaveStartWavelength {
            get {
                return ((double)(this["SaveStartWavelength"]));
            }
            set {
                this["SaveStartWavelength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1031")]
        public double SaveEndWavelength {
            get {
                return ((double)(this["SaveEndWavelength"]));
            }
            set {
                this["SaveEndWavelength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public global::spectra.state.Options.RangeUnits SaveRangeUnits {
            get {
                return ((global::spectra.state.Options.RangeUnits)(this["SaveRangeUnits"]));
            }
            set {
                this["SaveRangeUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"spectra_spectrum.csv\"")]
        public string SaveFileName {
            get {
                return ((string)(this["SaveFileName"]));
            }
            set {
                this["SaveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReferenceType {
            get {
                return ((int)(this["ReferenceType"]));
            }
            set {
                this["ReferenceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ResultSpectrumType {
            get {
                return ((int)(this["ResultSpectrumType"]));
            }
            set {
                this["ResultSpectrumType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumberOfSpectraForDynamicAccumulation {
            get {
                return ((int)(this["NumberOfSpectraForDynamicAccumulation"]));
            }
            set {
                this["NumberOfSpectraForDynamicAccumulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlotThresholds {
            get {
                return ((bool)(this["PlotThresholds"]));
            }
            set {
                this["PlotThresholds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint StaticReferenceAccumulateTime {
            get {
                return ((uint)(this["StaticReferenceAccumulateTime"]));
            }
            set {
                this["StaticReferenceAccumulateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint IntervalForDynamicAccumulation {
            get {
                return ((uint)(this["IntervalForDynamicAccumulation"]));
            }
            set {
                this["IntervalForDynamicAccumulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<spectra.processing.Wavelength> Wavelengths {
            get {
                return ((global::System.Collections.Generic.List<spectra.processing.Wavelength>)(this["Wavelengths"]));
            }
            set {
                this["Wavelengths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public uint NumberOfTimePointsToStore {
            get {
                return ((uint)(this["NumberOfTimePointsToStore"]));
            }
            set {
                this["NumberOfTimePointsToStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlotTriggerPoints {
            get {
                return ((bool)(this["PlotTriggerPoints"]));
            }
            set {
                this["PlotTriggerPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public uint NumberOfTriggerPoints {
            get {
                return ((uint)(this["NumberOfTriggerPoints"]));
            }
            set {
                this["NumberOfTriggerPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveWavelengthRange {
            get {
                return ((bool)(this["SaveWavelengthRange"]));
            }
            set {
                this["SaveWavelengthRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint NumberOfTimePointsToPlot {
            get {
                return ((uint)(this["NumberOfTimePointsToPlot"]));
            }
            set {
                this["NumberOfTimePointsToPlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveFileNameAutoUpdate {
            get {
                return ((bool)(this["SaveFileNameAutoUpdate"]));
            }
            set {
                this["SaveFileNameAutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SaveStepPixel {
            get {
                return ((int)(this["SaveStepPixel"]));
            }
            set {
                this["SaveStepPixel"] = value;
            }
        }
    }
}
